name: Build and Publish Wheel for DeepSpeed

on:
  push:
    tags:
      - 'deepspeed-*'

jobs:
  build-and-release:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.11.7]

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Visual C++ Build Tools
      run: |
        choco install visualcpp-build-tools -y

    - name: Clone DeepSpeed repository
      run: git clone --depth 1 --branch 0.11.1 https://github.com/microsoft/DeepSpeed.git

    - name: Install dependencies
      run: |
        pip install torch --index-url https://download.pytorch.org/whl/cu121

    - name: Modify DeepSpeed setup files
      run: |
        cd deepspeed
        git apply ../patches/deepspeed/deepspeed-win.patch

    - name: Build DeepSpeed
      run: |
        cd DeepSpeed
        python setup.py bdist_wheel

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Wheel to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: deepspeed/dist/deepspeed-0.11.1+9911c574-cp311-cp311-win_amd64.whl
        asset_name: deepspeed-0.11.1+9911c574-cp311-cp311-win_amd64.whl
        asset_content_type: application/octet-stream